---
# roles/virtualbox/tasks/ubuntu_12.04.yml

## We update our cache here in case we are removing, reinstalling or purging

- name: update apt cache
  apt: update_cache=yes cache_valid_time=43200
  tags: [ 'packages', 'virtualbox' ]

## Confirm that the value of ensure_virtualbox is valid

- fail: msg="ensure_virtualbox == {{ ensure_virtualbox }}. It must be equal installed, removed, reinstalled or purged."
  when: ensure_virtualbox != "installed" and ensure_virtualbox != "purged" and ensure_virtualbox != "reinstalled" and ensure_virtualbox != "removed"
  tags: [ 'packages', 'virtualbox' ]

## Removing Virtualbox

- name: Remove VirtualBox
  apt: pkg=virtualbox-{{ ubuntu_12_04_virtualbox_version }} state=absent purge=no
  when: ensure_virtualbox == "removed" or ensure_virtualbox == "reinstalled"
  tags: [ 'packages', 'virtualbox' ]

- name: Remove VirtualBox and purge the Virtualbox configuration files
  apt: pkg=virtualbox-{{ ubuntu_12_04_virtualbox_version }} state=absent purge=yes
  when: ensure_virtualbox == "purged"
  tags: [ 'packages', 'virtualbox' ]

- name: Remove the Oracle APT key
  apt_key: id=98AB5139 state=absent
  when: ensure_virtualbox == "removed" or ensure_virtualbox == "purged" or ensure_virtualbox == "reinstalled"
  tags: [ 'packages', 'virtualbox' ]

- name: Remove the VirtualBox APT repositories
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
                  state=absent
  when: ensure_virtualbox == "removed" or ensure_virtualbox == "purged" or ensure_virtualbox == "reinstalled"
  tags: [ 'packages', 'virtualbox' ]

## Installing Virtualbox

- name: Configure the Oracle APT key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc
           state=present
  when: ensure_virtualbox == "installed" or ensure_virtualbox == "reinstalled"
  tags: [ 'packages', 'virtualbox' ]

- name: Configure the VirtualBox APT repositories
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    mode: 0644
    state: present
  when: ensure_virtualbox == "installed" or ensure_virtualbox == "reinstalled"
  tags: [ 'packages', 'virtualbox' ]

- name: update apt cache
  apt: update_cache=yes cache_valid_time=43200
  when: ensure_virtualbox == "installed" or ensure_virtualbox == "reinstalled"
  tags: [ 'packages' ]

- name: Install VirtualBox
  apt: pkg=virtualbox-{{ ubuntu_12_04_virtualbox_version }} state=present
  when: ensure_virtualbox == "installed" or ensure_virtualbox == "reinstalled"
  tags: [ 'packages', 'virtualbox' ]
