---
# roles/tasks/ubuntu-14.04.yml for virtualbox

###  sudo apt-cache rdepends virtualbox-5.0

## Removing Virtualbox

- name: Remove VirtualBox
  apt: pkg=virtualbox-{{ ubuntu_14_04_virtualbox_version }} state=absent purge=no
  when: remove_virtualbox == true and purge_virtualbox == false

- name: Remove VirtualBox and purge the Virtualbox configuration files
  apt: pkg=virtualbox-{{ ubuntu_14_04_virtualbox_version }} state=absent purge=yes
  when: purge_virtualbox == true

# run **apt-key list** to find the apt-key id (below it is 281DDC4B)
#pub   1024D/98AB5139 2010-05-18
#uid                  Oracle Corporation (VirtualBox archive signing key) <info@virtualbox.org>
#sub   2048g/281DDC4B 2010-05-18


- name: Remove the Oracle APT key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc id=281DDC4B
           state=absent
  when: remove_virtualbox == true or purge_virtualbox == true

- name: Remove the VirtualBox APT repositories
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
                  state=absent
  when: remove_virtualbox == true or purge_virtualbox == true


## Installing Virtualbox

- name: Configure the Oracle APT key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc
           state=present
  when: install_virtualbox == true

- name: Configure the VirtualBox APT repositories
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
                  state=present
  when: install_virtualbox == true

- name: Install VirtualBox
  apt: pkg=virtualbox-{{ ubuntu_14_04_virtualbox_version }} state=present
  when: install_virtualbox == true


